### ISSUE TITLE
Increase the distance of detection.

### ISSUE THREAD

**Issue by rashmisgh** [vudung45/FaceRec#11]
Hey your work is great i implemented it and it works good.
This is not an error just a general question. can the distance of detecting the faces be increased?if yes then how to do that?? Do help me and thanks in advance.

**Comment by vudung45** [comment]
you can increase the distance by decreasing the min face size
‘’
 rects, landmarks = face_detect.detect_face(frame,80);#min face size is set to 80x80
‘’

Tune 80 into a suitable number. This will strip away performance and accuracy so please tune it accordingly

**Comment by rashmisgh** [comment]
Thanks a lot.

**Comment by rashmisgh** [comment]
will this work with tensorflow-gpu ??

**Comment by SourabhMane** [comment]
new_name = raw_input('Enter full name of the person: ').lower().strip();
    f = open('./facerec_128D.txt','r');
    data_set = json.loads(f.read());
    if new_name in data_set:
        print "%s already exists" %new_name
        create_manual_data()


steps to validate if user is already present in the file!!!

**Comment by rashmisgh** [comment]
Thanks @SourabhMane 
1 more problem plz help with this also. I need to give an image as input user and as the detection starts with a camera we can recognize that person with the label.
