### ISSUE TITLE
Is it really learning during recognition????

### ISSUE THREAD

**Issue by SourabhMane** [vudung45/FaceRec#12]
I dont know whether its learning the face during recognition.If yes please let me know

**Comment by vudung45** [comment]
With the current implementation, the input images are not "learned" during
the facial recognition process. However, implementing this wouldn't be too
difficult.

The current implementation generates 128D vector of a face, then compare
the distance of that vector to the ones stored in the user dataset. If the
distance to the closest vector in the dataset satisfies the distance
threshold (which is set to 0.6 by default), the person in the image would
then be "labeled" accordingly.

I'm assuming that you are referring to the feature which exists in Android
FaceID, or Apple FaceID. To implement something like that, you would have
to add a method to tune the current 128D vector in the dataset as the
person gets recognized by the program. This isn't difficult but it will
require some rigorous real-world testing to find an optimal algorithm.

Hope this helps!

**Comment by SourabhMane** [comment]
Thanks for quick reply...

I have few more questions.

1. What is the exact  difference between your FACEREC and David Sandberg's FACENET? Is the learning process implemented in the latter?

2. I would like to know whether the same Facerec implementation can work for database of 50,000 or more? How would be the accuracy level for recognition?   

3. Which of the two among  [Openface](https://github.com/cmusatyalab/openface) and  [Facenet](https://github.com/davidsandberg/facenet) gives better results under below mentioned scenario's
Scenario 1: If database consists of 5000 - 50,000 classes(people).
Scenario 2: If database consists of 1 Million - 10 Million classes(people)
