### ISSUE TITLE
Camera Feed Not Able To View

### ISSUE THREAD

**Issue by SalsHacker** [vudung45/FaceRec#23]
I have run the  main.py and it has worked but when I try to add a new user it does not show me the camera feed for the training.

**Comment by vudung45** [comment]
Please run main.py as the following command
`python3 main.py --mode "input"`

**Comment by SalsHacker** [comment]
Hi David,I am curious to know how the training works could you please explain to me how the training process is so quick and efficient.Could you please explain the code for the training.
