### ISSUE TITLE
finetuning the checkpoint

### ISSUE THREAD

**Issue by Zumbalamambo** [vudung45/FaceRec#5]
Thank you for your awesome work. Can you please tell me how I can fine tune the existing checkpoint with asian faces?

**Comment by vudung45** [comment]
@Zumbalamambo You can lower the distance threshold, now it's currently 0.6 I believe. I'm not sure if that would work better with asian faces, but it will surely avoid false negatives

**Comment by Zumbalamambo** [comment]
Thank you. That worked. is there any ways to boost the training process where it generates the embedding and writes to json? is it slow because each and every time it has to load the existing json and append the new feature array?

**Comment by vudung45** [comment]
@Zumbalamambo it is slow mainly because the process to generate embeddings requires quite a bit computing power from the CPU. If you are running tensorflow on a GPU, it should be fairly quick. However, I tested this code on my macbook pro, and the fps was somewhat smoother than I expected.

**Comment by Zumbalamambo** [comment]
yes... inference is awesome... while training, after pressing 'q', it takes a lot of time to train... is it because it has to generate feature array ? or is it slow because it has to rewrite the entire data?

**Comment by vudung45** [comment]
@Zumbalamambo mostly because it has to generate the embeddings

**Comment by Zumbalamambo** [comment]
okay... thanks
