### ISSUE TITLE
About align_custom.py

### ISSUE THREAD

**Issue by justyine** [vudung45/FaceRec#7]
Hi, 
I'm trying to understand the function of find_tfrom_between_shapes(), can you explain what algorithm did you use? 
And how did you come up with  average position of face points of below?
mean_face_shape_x = [0.224152, 0.75610125, 0.490127, 0.254149, 0.726104]
mean_face_shape_y = [0.2119465, 0.2119465, 0.628106, 0.780233, 0.780233]

**Comment by vudung45** [comment]
@justyine I extracted them from Dlib source code. Those numbers are the common aspect ratio of the 5 landmarks used for the alignment algoirthm

**Comment by Zumbalamambo** [comment]
@vudung45 is it possible to get the up and down position of head as well as the user rotates his head upwards or downwards so we can generate embedding for that as well?

**Comment by vudung45** [comment]
@Zumbalamambo Currently I only divides the head into 3 positions: "Left, Center, Right". You can play around with that by messing with the facial landmarks. 

Hope this helps

**Comment by rashmisgh** [comment]
@Zumbalamambo have you tried with the up & down position of the head and rotation? In the align_custom.py what is the thing we need to change?
