### ISSUE TITLE
Models Issue

### ISSUE THREAD

**Issue by TMALong** [vudung45/FaceRec#8]
InvalidArgumentError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to get matching files on models/model-20170512-110547.ckpt-250000: Not found: models
	 [[Node: save/RestoreV2_2 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_2/tensor_names, save/RestoreV2_2/shape_and_slices)]]

I downloaded the models in link and extract those to folder models.

**Comment by zerofeng11** [comment]
you need to change the paths in the models "fact_feature.py" .
